spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db1?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=SALEHANOMAN

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf cache off (????????????? ????)

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
spring.thymeleaf.cache=false


spring.thymeleaf.mode=HTML
spring.thymeleaf.check-template-location=true


spring.security.login.success-url=/
spring.security.login.failure-url=/login?error



logging.level.org.hibernate.SQL=DEBUG  # ??????? ??????? ?????
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE  # ???? ???????? ?????


logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.example.ecommerce=DEBUG

logging.level.org.hibernate.orm.jdbc.bind=TRACE
server.error.whitelabel.enabled=false


spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
# ???? ?????? ?????? (?? ?????? ????)



spring.security.form-login.default-success-url=/
spring.security.form-login.always-use-default=false



server.servlet.session.cookie.same-site=LAX
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.http-only=true

server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.timeout=30m

spring.websocket.stomp-endpoint=/ws
spring.websocket.message-broker=/topic
spring.websocket.application-destination=/app

server.port=8080